### ISSUE TITLE
關於其它的 Office config xml 配置工具

### ISSUE THREAD

**Issue by pzhlkj6612** [kuarcis/Office_C2R_installer#1]
你好，今天逛 GitHub，偶然看到你的 Repo。剛讀了下 README，發現你提到：

> but the installer he made always trigger my antivirus alert, so, I made another one, with source code.

我猜這是 KMSAuto Net 2015 導致的，你看看 Office_2013-2016_C2R_Install 壓縮包裏的readme，有提到。

如果你僅僅是做一個 xml 配置工具，那應該就不會有任何的問題了（關於反病毒），而且也應該會更輕量。

順便，有一個 [Office Tool Plus](https://otp.landian.la/index.html) ，我還沒有用過，你可以去瞧一瞧？找一些可能學習到的地方。

期待你的作品。

**Comment by kuarcis** [comment]
感謝你的建議，原本製作這個工具的用意是方便安裝而已，對於有正版cdkey的人，似乎連下載功能都有點多餘(正版購買後可憑cdkey自微軟直接下載iso檔)，所以才做了這個羽量級功能的安裝器。
因為本身還有其他工作正在進行，基本上這個工具也已經達到了我的目的，短期內應該不會有甚麼變化，最多就加入簡繁體中文吧我想。
不管如何，還是謝謝你提供的資訊跟建議

**Comment by pzhlkj6612** [comment]
好的，不謝呢~

<br/>

呃，另外我想問下：

> kuarcis self-assigned this 4 days ago

這裏的*self-assigned*是個什麽意思啊，之前去網上找了找卻并無結果，想請解答下，謝謝。

**Comment by kuarcis** [comment]
可以支派issue給某個有授權的人做處理的意思

Mozi <notifications@github.com> 於 2018年3月21日 週三 下午12:22 寫道：

**Comment by pzhlkj6612** [comment]
好的，我想我還是需要自己去使用才能知道究竟會有怎麽樣的效果；謝謝你。
